#!/usr/bin/python3.8
import os
import sys
import time
import subprocess

def file_filter(name):
    return (not name.startswith(".")) and (not name.endswith(".swp"))


def file_times(path):
    for top_level in filter(file_filter, os.listdir(path)):
        yield os.stat(os.path.join(os.path.abspath(path), top_level)).st_mtime


def print_stdout(process):
    stdout = process.stdout
    if stdout != None:
        print(stdout)


# We concatenate all of the arguments together, and treat that as the command to run
command ='clear;' + sys.argv[1] + ' ' + os.path.join(os.path.abspath('.'), ' '.join(sys.argv[2:]))

# The path to watch
path = '.'

# How often we check the filesystem for changes (in seconds)
wait = 1

# The process to autoreload
process = subprocess.Popen(command, shell=True)

# The current maximum file modified time under the watched directory
last_mtime = max(file_times(path))


while True:
    max_mtime = max(file_times(path))
    print_stdout(process)
    if max_mtime > last_mtime:
        last_mtime = max_mtime
        print('[bold blue]Restarting process.[/]')
        process.kill()
        process = subprocess.Popen(command, shell=True)
    time.sleep(wait)
